/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-03-22 23:51:27 
*/
import { Direction } from "./direction";
import { Plateau } from "./plateau";
import { State } from "./state";
import { Coordinate } from "./coordinate";

export interface IRover {
    state: State;
    plateau: Plateau;
    move(): void;
    turn(turnCommand: string): void;
}
